name: Crawl Data

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  crawl:
    name: Crawl Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install Packages
        run: npm install
      - name: Crawl
        run: node script/crawler.js
      - name: Commit to Data Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: "./data"
          user_name: "JacobLinCool"
          user_email: "jacoblincool@users.noreply.github.com"
          publish_branch: "data"
          keep_files: true